#!/usr/bin/env bash

### infomation ###
if [ $# -eq 0 ]; then
    printf '%s\n' \
        'Enter your options.' \
        'manage -help : infomation'
    exit 1
fi

if [ $1 = '-help' ]; then
    printf '%s\n' \
        '--------- opstions ----------' \
        '-help : infomation' \
        '-bash : Bash configuration' \
        '-nvim : Neovim configration' \
        '-tmux : Tmux configration' \
        '-----------------------------'
fi

### setting bash ###
if [ $1 = '-bash' ]; then
    if [ -h ~/.bashrc_origin ]; then
        :
    else
        ln -s ~/.dotfiles/config/bash/.bashrc_origin ~/.bashrc_origin
    fi
fi

### setting nvim ###
if [ $1 = '-nvim' ]; then
    sudo apt update
    sudo apt install neovim

    cd ~/.config/nvim/ 2>/dev/null
    if [ $? = 1 ]; then
        mkdir ~/.config/nvim
        cd ~/.config/nvim/
    fi

    if [ -h ~/.config/nvim/init.vim ]; then
        :
    else
        ln -s ~/.dotfiles/config/neovim/init.vim ~/.config/nvim/init.vim
    fi
fi

### setting tmux ###
if [ $1 = '-tmux' ]; then
    sudo apt update
    sudo apt install tmux

    if [ -h ~/.tmux.conf ]; then
        :
    else
        ln -s ~/.dotfiles/config/tmux/.tmux.conf ~/.tmux.conf
    fi
fi
